/*
  The Red Archive — DemonTime lore code archive
  Generated from HeavenArchiveUnlocks.java so the website mirrors the current Heavenly Book archive.

  Each entry code is the in-game archive id converted to uppercase with hyphens.
  Example: heaven_dimension -> HEAVEN-DIMENSION

  Lore text supports Minecraft formatting codes:
  §k obfuscated, §l bold, §o italic, §n underline, §m strikethrough, §r reset,
  §0-§f color codes, and Java hex colors like §x§f§f§0§0§0§0.
*/

const RED_ARCHIVE_RECORDS = [
  {
    "code": "HEAVEN-DIMENSION",
    "sourceId": "heaven_dimension",
    "title": "Heaven Dimension",
    "hiddenTitle": "Unknown Dimension",
    "category": "Heaven",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:heavendimension|heavendimension|dimension/heavendimension",
    "threat": "Discovery Record // Heaven",
    "body": "A real current dimension in the mod. The Archive marks it when the player reaches the Heaven realm."
  },
  {
    "code": "SKY-BREACH",
    "sourceId": "sky_breach",
    "title": "Sky Breach",
    "hiddenTitle": "Unknown Sky Threshold",
    "category": "Heaven",
    "triggerType": "discovery",
    "triggerId": "y400|heaven_dimension_transport|demontimessntwo:heavendimension",
    "threat": "Discovery Record // Heaven",
    "body": "The current Heaven transport route: climb high enough and the sky itself becomes the doorway."
  },
  {
    "code": "HEAVEN-BIOME",
    "sourceId": "heaven_biome",
    "title": "Heaven Biome",
    "hiddenTitle": "Unknown Heaven Biome",
    "category": "Heaven",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:heavenbiome|heavenbiome",
    "threat": "Discovery Record // Heaven",
    "body": "The active Heaven biome currently generated by the mod."
  },
  {
    "code": "CLOUD-BLOCK",
    "sourceId": "cloud_block",
    "title": "Cloud Block",
    "hiddenTitle": "Unknown Cloud Matter",
    "category": "Heaven",
    "triggerType": "block",
    "triggerId": "demontimessntwo:cloud_block",
    "threat": "Block Contact // Heaven",
    "body": "A placeable cloud material tied to Heaven traversal and atmosphere."
  },
  {
    "code": "HEAVENLY-WOOD-FAMILY",
    "sourceId": "heavenly_wood_family",
    "title": "Heavenly Wood Set",
    "hiddenTitle": "Unknown Pale Wood",
    "category": "Heaven",
    "triggerType": "block",
    "triggerId": "demontimessntwo:heavenly_log|demontimessntwo:heavenly_wood|demontimessntwo:stripped_heavenly_log|demontimessntwo:stripped_heavenly_wood|demontimessntwo:heavenly_planks|demontimessntwo:heavenly_leaves",
    "threat": "Block Contact // Heaven",
    "body": "The current Heaven tree/building family: logs, wood, stripped wood, planks, leaves, stairs, slabs, fences, doors, signs, and trapdoors."
  },
  {
    "code": "HEAVENLY-FORGE",
    "sourceId": "heavenly_forge",
    "title": "Heavenly Forge",
    "hiddenTitle": "Unknown Divine Workstation",
    "category": "Heaven",
    "triggerType": "block",
    "triggerId": "demontimessntwo:heavenly_forge",
    "threat": "Block Contact // Heaven",
    "body": "A real progression workstation in the mod, used for divine and higher-tier crafting paths."
  },
  {
    "code": "HEAVENLY-ALTAR",
    "sourceId": "heavenly_altar",
    "title": "Heavenly Altar",
    "hiddenTitle": "Unknown Altar",
    "category": "Heaven",
    "triggerType": "block",
    "triggerId": "demontimessntwo:heavenly_altar",
    "threat": "Block Contact // Heaven",
    "body": "A current altar block used by the Heaven systems."
  },
  {
    "code": "HEAVENLY-CACHE-BOX",
    "sourceId": "heavenly_cache_box",
    "title": "Heavenly Cache Box",
    "hiddenTitle": "Unknown Cache",
    "category": "Heaven",
    "triggerType": "block",
    "triggerId": "demontimessntwo:heavenly_cache_box",
    "threat": "Block Contact // Heaven",
    "body": "A current Heaven cache container, meant to tie loot and keys into progression."
  },
  {
    "code": "PURIFIER",
    "sourceId": "purifier",
    "title": "Purifier",
    "hiddenTitle": "Unknown Purifier",
    "category": "Heaven",
    "triggerType": "block",
    "triggerId": "demontimessntwo:purifier",
    "threat": "Block Contact // Heaven",
    "body": "A real current purifier block for cleaning, restoring, and converting corrupted materials."
  },
  {
    "code": "FALLEN-HEAVENS",
    "sourceId": "fallen_heavens",
    "title": "Fallen Heavens",
    "hiddenTitle": "Unknown Fallen Biome",
    "category": "Fallen Heavens",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens|fallen_heavens",
    "threat": "Discovery Record // Fallen Heavens",
    "body": "The current rare Overworld scar biome: Heaven forced into the ground and burned wrong."
  },
  {
    "code": "FALLEN-HEAVENS-FRINGE",
    "sourceId": "fallen_heavens_fringe",
    "title": "Fallen Heavens Fringe",
    "hiddenTitle": "Unknown Fringe",
    "category": "Fallen Heavens",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_fringe|fallen_heavens_fringe|fringe",
    "threat": "Discovery Record // Fallen Heavens",
    "body": "The current outer Fallen Heavens biome zone where normal life still pushes against the scar."
  },
  {
    "code": "ASH-COVERED-DIRT",
    "sourceId": "ash_covered_dirt",
    "title": "Ash Covered Dirt",
    "hiddenTitle": "Unknown Ashen Ground",
    "category": "Fallen Heavens",
    "triggerType": "block",
    "triggerId": "demontimessntwo:ash_covered_dirt",
    "threat": "Block Contact // Fallen Heavens",
    "body": "A current Fallen Heavens ground block used around burned areas and ruins."
  },
  {
    "code": "CHARRED-WOOD-FAMILY",
    "sourceId": "charred_wood_family",
    "title": "Charred Wood Set",
    "hiddenTitle": "Unknown Burned Wood",
    "category": "Fallen Heavens",
    "triggerType": "block",
    "triggerId": "demontimessntwo:charred_log|demontimessntwo:charred_wood|demontimessntwo:stripped_charred_log|demontimessntwo:stripped_charred_wood|demontimessntwo:charred_planks|demontimessntwo:charred_stairs|demontimessntwo:charred_slab|demontimessntwo:charred_fence|demontimessntwo:charred_fence_gate|demontimessntwo:charred_door|demontimessntwo:charred_trapdoor|demontimessntwo:charred_leaves",
    "threat": "Block Contact // Fallen Heavens",
    "body": "The current burned wood family used in Fallen Heavens ruins and created by the charred-wood burning handler."
  },
  {
    "code": "CHARRED-BOATS",
    "sourceId": "charred_boats",
    "title": "Charred Boats",
    "hiddenTitle": "Unknown Burned Boat",
    "category": "Fallen Heavens",
    "triggerType": "item",
    "triggerId": "demontimessntwo:charred_boat|demontimessntwo:charred_chest_boat",
    "threat": "Item Recovered // Fallen Heavens",
    "body": "Current charred boat items and entities registered outside the generated MCreator files."
  },
  {
    "code": "COSMIC-DEMON-ARENA",
    "sourceId": "cosmic_demon_arena",
    "title": "Cosmic Demon Arena",
    "hiddenTitle": "Unknown Arena",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:cosmic_demon_arena|demontimessntwo:cosmic_demon_ruins/arena|cosmic_demon_summoning_altar",
    "threat": "Discovery Record // Structures",
    "body": "The active arena structure for the Cosmic Demon encounter, including barrels and the summoning altar."
  },
  {
    "code": "FALLEN-RUINS-NETWORK",
    "sourceId": "fallen_ruins_network",
    "title": "Fallen Heavens Ruins Network",
    "hiddenTitle": "Unknown Ruin Network",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_ruins|demontimessntwo:cosmic_demon_ruins|complete_arena_network",
    "threat": "Discovery Record // Structures",
    "body": "The current ruin network around the arena: spokes, satellite ruins, and the connected fallen village feel."
  },
  {
    "code": "BROKEN-CHURCH",
    "sourceId": "broken_church",
    "title": "Broken Church",
    "hiddenTitle": "Unknown Church",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_ruins/broken_church|broken_church",
    "threat": "Discovery Record // Structures",
    "body": "A current Fallen Heavens satellite structure: a broken church connected to the ruin path system."
  },
  {
    "code": "CHARRED-HOUSE",
    "sourceId": "charred_house",
    "title": "Charred House",
    "hiddenTitle": "Unknown Burned House",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_ruins/charred_house|charred_house",
    "threat": "Discovery Record // Structures",
    "body": "A current ruined house structure using charred wood and broken path blocks."
  },
  {
    "code": "CHARRED-BUILDING",
    "sourceId": "charred_building",
    "title": "Charred Building",
    "hiddenTitle": "Unknown Burned Building",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_ruins/charred_building|charred_building",
    "threat": "Discovery Record // Structures",
    "body": "A current small burned building used in the Fallen Heavens ruin set."
  },
  {
    "code": "FOUNTAIN",
    "sourceId": "fountain",
    "title": "Fallen Fountain",
    "hiddenTitle": "Unknown Fountain",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_ruins/fountain|fountain",
    "threat": "Discovery Record // Structures",
    "body": "A current fountain satellite ruin built with slate, stone columns, water, and broken polish."
  },
  {
    "code": "PATH-REMNANT",
    "sourceId": "path_remnant",
    "title": "Path Remnant",
    "hiddenTitle": "Unknown Broken Path",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_ruins/path_remnant|path_remnant|spokes",
    "threat": "Discovery Record // Structures",
    "body": "Current path pieces made from andesite, cobble, and gravel to connect the ruins."
  },
  {
    "code": "SMALL-ALTAR",
    "sourceId": "small_altar",
    "title": "Small Altar",
    "hiddenTitle": "Unknown Black Altar",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:fallen_heavens_ruins/small_altar|small_altar",
    "threat": "Discovery Record // Structures",
    "body": "A current satellite altar built with black marble, candles, skulls, and charred stairs."
  },
  {
    "code": "FORGE-STRUCTURE",
    "sourceId": "forge_structure",
    "title": "Forge Structure",
    "hiddenTitle": "Unknown Forge Structure",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:forge_structure|forge_structure",
    "threat": "Discovery Record // Structures",
    "body": "A current worldgen structure tied to the mod's forge progression."
  },
  {
    "code": "STAR-CLUSTER-STRUCTURE",
    "sourceId": "star_cluster_structure",
    "title": "Star Cluster Structure",
    "hiddenTitle": "Unknown Star Cluster",
    "category": "Structures",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:star_cluster_structure|star_cluster",
    "threat": "Discovery Record // Structures",
    "body": "A current structure connected to the star-metal and falling-star side of progression."
  },
  {
    "code": "CHOIR-WISP",
    "sourceId": "choir_wisp",
    "title": "Choir Wisp",
    "hiddenTitle": "Unknown Choir Light",
    "category": "Mobs",
    "triggerType": "discovery",
    "triggerId": "demontimessntwo:wisp|wisp|choir_wisp",
    "threat": "Discovery Record // Mobs",
    "body": "A rare Heaven spirit that hovers with a combined flap-and-hover idle. It blesses wounded allies, flees danger, and punishes anyone who strikes it with a brief holy backlash."
  },
  {
    "code": "ANGELIC-CHICKEN",
    "sourceId": "angelic_chicken",
    "title": "Angelic Chicken",
    "hiddenTitle": "Unknown Angelic Creature",
    "category": "Mobs",
    "triggerType": "kill",
    "triggerId": "demontimessntwo:angelicchicken|angelicchicken",
    "threat": "Kill Record // Mobs",
    "body": "The current Heaven mob. It looks harmless, but the Archive knows it belongs to a divine ecosystem."
  },
  {
    "code": "COSMIC-DEMON",
    "sourceId": "cosmic_demon",
    "title": "Cosmic Demon",
    "hiddenTitle": "Unknown Cosmic Boss",
    "category": "Bosses",
    "triggerType": "kill",
    "triggerId": "demontimessntwo:cosmicdemon|cosmicdemon",
    "threat": "Kill Record // Bosses",
    "body": "The current major boss: a huge black-hole-themed demon tied to the arena, altar, and Titan Remnant progression."
  },
  {
    "code": "ANGELIC-FEATHER",
    "sourceId": "angelic_feather",
    "title": "Angelic Feather",
    "hiddenTitle": "Unknown Feather",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:angelic_feather",
    "threat": "Item Recovered // Relics",
    "body": "A current drop/material from Heaven-aligned life."
  },
  {
    "code": "GILDED-FEATHER",
    "sourceId": "gilded_feather",
    "title": "Gilded Feather",
    "hiddenTitle": "Unknown Gilded Feather",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:gildedfeather|demontimessntwo:gilded_feather",
    "threat": "Item Recovered // Relics",
    "body": "A current upgraded feather material for divine progression."
  },
  {
    "code": "DIVINE-HALO",
    "sourceId": "divine_halo",
    "title": "Divine Halo",
    "hiddenTitle": "Unknown Halo",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:divine_halo_helmet",
    "threat": "Item Recovered // Relics",
    "body": "A current wearable Heaven relic registered as armor."
  },
  {
    "code": "HEAVENLY-STICK",
    "sourceId": "heavenly_stick",
    "title": "Heavenly Stick",
    "hiddenTitle": "Unknown Heavenly Rod",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:heavenly_stick|demontimessntwo:enchanted_heavenly_stick",
    "threat": "Item Recovered // Relics",
    "body": "The current basic and enchanted stick materials used in Heaven crafting paths."
  },
  {
    "code": "HEAVENS-WRATH",
    "sourceId": "heavens_wrath",
    "title": "Heaven's Wrath",
    "hiddenTitle": "Unknown Heaven Weapon",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:heavens_wrath|demontimessntwo:true_heavens_wrath",
    "threat": "Item Recovered // Relics",
    "body": "The current Heaven weapon path, including the higher True Heaven's Wrath item."
  },
  {
    "code": "BLACKHOLE-CORE",
    "sourceId": "blackhole_core",
    "title": "Blackhole Core",
    "hiddenTitle": "Unknown Singularity Core",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:blackholecore|demontimessntwo:blackhole_core_item",
    "threat": "Item Recovered // Relics",
    "body": "A current black-hole core item tied to Cosmic Demon and staff progression."
  },
  {
    "code": "BLACKHOLE-STAFFS",
    "sourceId": "blackhole_staffs",
    "title": "Blackhole Staff Line",
    "hiddenTitle": "Unknown Gravity Staff",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:blackhole_staff|demontimessntwo:stabilized_blackhole_staff|demontimessntwo:event_horizon_staff|demontimessntwo:singularity_staff",
    "threat": "Item Recovered // Relics",
    "body": "The current black-hole staff progression line: base, stabilized, event-horizon, and singularity tiers."
  },
  {
    "code": "BLACK-HOLE-RING",
    "sourceId": "black_hole_ring",
    "title": "Black Hole Ring",
    "hiddenTitle": "Unknown Black-Hole Bauble",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:black_hole_ring",
    "threat": "Item Recovered // Relics",
    "body": "A current Curios bauble and rare black-hole reward."
  },
  {
    "code": "ANGELIC-FEATHER-CHARM",
    "sourceId": "angelic_feather_charm",
    "title": "Angelic Feather Charm",
    "hiddenTitle": "Unknown Angelic Charm",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:angelic_feather_charm",
    "threat": "Item Recovered // Relics",
    "body": "A current Curios charm made from angelic materials."
  },
  {
    "code": "TITAN-REMNANT",
    "sourceId": "titan_remnant",
    "title": "Titan Remnant",
    "hiddenTitle": "Unknown Titan Relic",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:titan_remnant|demontimessntwo:titanremanent",
    "threat": "Item Recovered // Relics",
    "body": "A current core progression material tied to boss rewards and Titan paths."
  },
  {
    "code": "TITAN-REMNANT-VARIANTS",
    "sourceId": "titan_remnant_variants",
    "title": "Titan Remnant Variants",
    "hiddenTitle": "Unknown Altered Remnant",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:controlledtitanremanent|demontimessntwo:permanentlyconcealedtitanremanent|demontimessntwo:blessed_titan_remnant|demontimessntwo:concealed_titan_remnant|demontimessntwo:blood_stabilized_remnant",
    "threat": "Item Recovered // Relics",
    "body": "Current altered Titan Remnant forms used by purification and upgrade paths."
  },
  {
    "code": "TITAN-BAUBLES",
    "sourceId": "titan_baubles",
    "title": "Titan Baubles",
    "hiddenTitle": "Unknown Titan Bauble",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:titan_heart_pendant|demontimessntwo:titan_belt|demontimessntwo:reinforced_titan_belt|demontimessntwo:titan_bound_relic",
    "threat": "Item Recovered // Relics",
    "body": "Current Titan-themed Curios and relic upgrades."
  },
  {
    "code": "PURIFIER-CORES",
    "sourceId": "purifier_cores",
    "title": "Purifier Cores",
    "hiddenTitle": "Unknown Purifier Core",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:basic_purifier_core|demontimessntwo:angelic_core|demontimessntwo:celestial_core|demontimessntwo:abyssal_core|demontimessntwo:blood_core|demontimessntwo:verdant_core|demontimessntwo:infernal_core|demontimessntwo:echo_core",
    "threat": "Item Recovered // Relics",
    "body": "Current core items used by purifier and infusion progression."
  },
  {
    "code": "HEAVENLY-CACHE-KEYS",
    "sourceId": "heavenly_cache_keys",
    "title": "Heavenly Cache Keys",
    "hiddenTitle": "Unknown Cache Key",
    "category": "Relics",
    "triggerType": "item",
    "triggerId": "demontimessntwo:heavenly_cache_key_fragment|demontimessntwo:heavenly_cache_key",
    "threat": "Item Recovered // Relics",
    "body": "Current key items for the Heavenly Cache Box system."
  },
  {
    "code": "AEROLITE-MATERIALS",
    "sourceId": "aerolite_materials",
    "title": "Aerolite Materials",
    "hiddenTitle": "Unknown Pale Metal",
    "category": "Materials",
    "triggerType": "item",
    "triggerId": "demontimessntwo:aerolite_chunk|demontimessntwo:aerolite_ingot|demontimessntwo:aerolite_smithing_template|demontimessntwo:aerolite_ore|demontimessntwo:aerolite_block",
    "threat": "Item Recovered // Materials",
    "body": "Current Aerolite ore, chunk, ingot, block, and smithing-template material line."
  },
  {
    "code": "AEROLITE-TOOLS",
    "sourceId": "aerolite_tools",
    "title": "Aerolite Tools",
    "hiddenTitle": "Unknown Aerolite Tool",
    "category": "Materials",
    "triggerType": "item",
    "triggerId": "demontimessntwo:aerolite_pickaxe|demontimessntwo:aerolite_axe|demontimessntwo:aerolite_sword|demontimessntwo:aerolite_shovel|demontimessntwo:aerolite_hoe|demontimessntwo:blessed_aerolite_sword|demontimessntwo:aerolite_utility_belt",
    "threat": "Item Recovered // Materials",
    "body": "Current Aerolite tool and utility equipment path."
  },
  {
    "code": "ASTRELIUM-MATERIALS",
    "sourceId": "astrelium_materials",
    "title": "Astrelium Materials",
    "hiddenTitle": "Unknown Star Metal",
    "category": "Materials",
    "triggerType": "item",
    "triggerId": "demontimessntwo:astrelium_chunk|demontimessntwo:astrelium_ingot|demontimessntwo:astrelium_smithing_template|demontimessntwo:astrelium_ore|demontimessntwo:astrelium_block",
    "threat": "Item Recovered // Materials",
    "body": "Current Astrelium ore, chunk, ingot, block, and smithing-template material line."
  },
  {
    "code": "ASTRELIUM-TOOLS",
    "sourceId": "astrelium_tools",
    "title": "Astrelium Tools",
    "hiddenTitle": "Unknown Astrelium Tool",
    "category": "Materials",
    "triggerType": "item",
    "triggerId": "demontimessntwo:astrelium_pickaxe|demontimessntwo:astrelium_axe|demontimessntwo:astrelium_sword|demontimessntwo:astrelium_shovel|demontimessntwo:astrelium_hoe|demontimessntwo:astrelium_war_belt",
    "threat": "Item Recovered // Materials",
    "body": "Current Astrelium tool and belt path."
  },
  {
    "code": "STAR-MATERIALS",
    "sourceId": "star_materials",
    "title": "Star Materials",
    "hiddenTitle": "Unknown Fallen Star Material",
    "category": "Materials",
    "triggerType": "item",
    "triggerId": "demontimessntwo:star_metal_fragment|demontimessntwo:fallen_star_core|demontimessntwo:cracked_star_shell|demontimessntwo:star_metal_ingot|demontimessntwo:celestial_singularity",
    "threat": "Item Recovered // Materials",
    "body": "Current falling-star and celestial materials."
  },
  {
    "code": "GRACE-MATERIALS",
    "sourceId": "grace_materials",
    "title": "Grace Materials",
    "hiddenTitle": "Unknown Grace Material",
    "category": "Materials",
    "triggerType": "item",
    "triggerId": "demontimessntwo:grace_dust|demontimessntwo:bottled_grace|demontimessntwo:grace_apple|demontimessntwo:grace_locket|demontimessntwo:celestial_amulet",
    "threat": "Item Recovered // Materials",
    "body": "Current grace-based materials, food, and baubles."
  },
  {
    "code": "STABILIZER-CIRCLE-BASIC",
    "sourceId": "stabilizer_circle_basic",
    "title": "Stabilizer Circle",
    "hiddenTitle": "Unknown Stabilizer Pattern",
    "category": "Rituals",
    "triggerType": "discovery",
    "triggerId": "stabilizer_circle_basic",
    "threat": "Discovery Record // Rituals",
    "body": "Four stabilizers around the Heavenly Altar form the simple circuit. It is enough for overlimit work to become controlled instead of reckless."
  },
  {
    "code": "STABILIZER-CIRCLE-ADVANCED",
    "sourceId": "stabilizer_circle_advanced",
    "title": "Advanced Stabilizer Circle",
    "hiddenTitle": "Unknown Advanced Pattern",
    "category": "Rituals",
    "triggerType": "discovery",
    "triggerId": "stabilizer_circle_advanced",
    "threat": "Discovery Record // Rituals",
    "body": "Eight stabilizers around the altar complete the full ring. The circle catches failed pressure and gives the altar a proper containment geometry."
  },
  {
    "code": "STABILIZER-LESSER",
    "sourceId": "stabilizer_lesser",
    "title": "Lesser Stabilizer",
    "hiddenTitle": "Unknown Stabilizer",
    "category": "Rituals",
    "triggerType": "block",
    "triggerId": "demontimessntwo:lesser_stabilizer",
    "threat": "Block Contact // Rituals",
    "body": "A basic stabilizer block. It adds weak stability and proves the circle is listening."
  },
  {
    "code": "STABILIZER-EMPOWERED",
    "sourceId": "stabilizer_empowered",
    "title": "Empowered Stabilizer",
    "hiddenTitle": "Unknown Empowered Stabilizer",
    "category": "Rituals",
    "triggerType": "block",
    "triggerId": "demontimessntwo:empowered_stabilizer",
    "threat": "Block Contact // Rituals",
    "body": "A stronger stabilizer for upgrade pressure. It improves success and helps protect against downgrade when used in a full ring."
  },
  {
    "code": "STABILIZER-CELESTIAL",
    "sourceId": "stabilizer_celestial",
    "title": "Celestial Stabilizer",
    "hiddenTitle": "Unknown Celestial Stabilizer",
    "category": "Rituals",
    "triggerType": "block",
    "triggerId": "demontimessntwo:celestial_stabilizer",
    "threat": "Block Contact // Rituals",
    "body": "A high-tier stabilizer that favors safe results. It helps protect the item from breaking under overlimit pressure."
  },
  {
    "code": "STABILIZER-TITAN",
    "sourceId": "stabilizer_titan",
    "title": "Titan Stabilizer",
    "hiddenTitle": "Unknown Titan Stabilizer",
    "category": "Rituals",
    "triggerType": "block",
    "triggerId": "demontimessntwo:titan_stabilizer",
    "threat": "Block Contact // Rituals",
    "body": "A heavy stabilizer that protects the item body. Titan stabilization is about endurance, not elegance."
  },
  {
    "code": "STABILIZER-VOLATILE",
    "sourceId": "stabilizer_volatile",
    "title": "Volatile Stabilizer",
    "hiddenTitle": "Unknown Volatile Stabilizer",
    "category": "Rituals",
    "triggerType": "block",
    "triggerId": "demontimessntwo:volatile_stabilizer",
    "threat": "Block Contact // Rituals",
    "body": "A dangerous stabilizer that feeds extra power into the circle. It can boost overlimit work, but it should never feel completely safe."
  },
  {
    "code": "BESTIARY-ANGELIC-CHICKEN-BASIC",
    "sourceId": "bestiary_angelic_chicken_basic",
    "title": "Angelic Chicken: Field Notes",
    "hiddenTitle": "Unknown Creature Notes",
    "category": "Bestiary",
    "triggerType": "kill",
    "triggerId": "demontimessntwo:angelicchicken|angelicchicken",
    "threat": "Kill Record // Bestiary",
    "body": "Bestiary tier 1: Angelic Chickens are Heaven-touched wildlife. They look soft, but their drops mark the first edge of divine ecology."
  },
  {
    "code": "BESTIARY-ANGELIC-CHICKEN-DROPS",
    "sourceId": "bestiary_angelic_chicken_drops",
    "title": "Angelic Chicken: Drops",
    "hiddenTitle": "Unknown Creature Drops",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_angelic_chicken@10",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 2: After studying enough Angelic Chickens, the Archive notes feather-based materials as the useful reward path."
  },
  {
    "code": "BESTIARY-ANGELIC-CHICKEN-WEAKNESS",
    "sourceId": "bestiary_angelic_chicken_weakness",
    "title": "Angelic Chicken: Weakness",
    "hiddenTitle": "Unknown Creature Weakness",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_angelic_chicken@25",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 3: They are not a true combat threat. The danger is letting Heaven feel harmless for too long."
  },
  {
    "code": "BESTIARY-CHOIR-WISP-BASIC",
    "sourceId": "bestiary_choir_wisp_basic",
    "title": "Choir Wisp: Field Notes",
    "hiddenTitle": "Unknown Wisp Notes",
    "category": "Bestiary",
    "triggerType": "kill",
    "triggerId": "demontimessntwo:choir_wisp|choir_wisp|wisp",
    "threat": "Kill Record // Bestiary",
    "body": "Bestiary tier 1: Choir Wisps are rare Heaven echoes. Their movement and pulse behavior make them feel less like animals and more like fragments of a song."
  },
  {
    "code": "BESTIARY-CHOIR-WISP-DROPS",
    "sourceId": "bestiary_choir_wisp_drops",
    "title": "Choir Wisp: Drops",
    "hiddenTitle": "Unknown Wisp Drops",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_choir_wisp@10",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 2: Enough encounters reveal that echo-themed materials belong to the Wisp's reward identity."
  },
  {
    "code": "BESTIARY-CHOIR-WISP-WEAKNESS",
    "sourceId": "bestiary_choir_wisp_weakness",
    "title": "Choir Wisp: Weakness",
    "hiddenTitle": "Unknown Wisp Weakness",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_choir_wisp@25",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 3: The Wisp is fragile when pressured. Stay close after it blinks away and do not let its pulse reset the fight."
  },
  {
    "code": "BESTIARY-COSMIC-DEMON-BASIC",
    "sourceId": "bestiary_cosmic_demon_basic",
    "title": "Cosmic Demon: Field Notes",
    "hiddenTitle": "Unknown Boss Notes",
    "category": "Bestiary",
    "triggerType": "kill",
    "triggerId": "demontimessntwo:cosmicdemon|cosmicdemon|cosmic_demon",
    "threat": "Kill Record // Bestiary",
    "body": "Bestiary tier 1: The Cosmic Demon is a gravity boss built around shield pressure, black-hole hazards, and rare singularity rewards."
  },
  {
    "code": "BESTIARY-COSMIC-DEMON-DROPS",
    "sourceId": "bestiary_cosmic_demon_drops",
    "title": "Cosmic Demon: Drops",
    "hiddenTitle": "Unknown Boss Drops",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_cosmic_demon@3",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 2: Repeated victories confirm its core rewards: Blackhole Core, Titan Remnant, Stabilized Blackhole Fragment, and the rarer Celestial Singularity."
  },
  {
    "code": "BESTIARY-COSMIC-DEMON-WEAKNESS",
    "sourceId": "bestiary_cosmic_demon_weakness",
    "title": "Cosmic Demon: Weakness",
    "hiddenTitle": "Unknown Boss Weakness",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_cosmic_demon@5",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 3: The shield cores are the opening. Break the orbiting protection, respect the black-hole pull, then punish the demon before the arena controls you."
  },
  {
    "code": "BESTIARY-FALLEN-SERAPH-BASIC",
    "sourceId": "bestiary_fallen_seraph_basic",
    "title": "Fallen Seraph: Field Notes",
    "hiddenTitle": "Unknown Seraph Notes",
    "category": "Bestiary",
    "triggerType": "kill",
    "triggerId": "demontimessntwo:fallen_seraph|fallen_seraph|fallenseraph",
    "threat": "Kill Record // Bestiary",
    "body": "Bestiary tier 1: The Fallen Seraph is not just a large enemy. Its phases are a sermon delivered with lasers, dives, halos, and gravity pins."
  },
  {
    "code": "BESTIARY-FALLEN-SERAPH-DROPS",
    "sourceId": "bestiary_fallen_seraph_drops",
    "title": "Fallen Seraph: Drops",
    "hiddenTitle": "Unknown Seraph Drops",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_fallen_seraph@3",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 2: Its rewards should support star-metal, fallen-star, and high Heaven progression paths."
  },
  {
    "code": "BESTIARY-FALLEN-SERAPH-WEAKNESS",
    "sourceId": "bestiary_fallen_seraph_weakness",
    "title": "Fallen Seraph: Weakness",
    "hiddenTitle": "Unknown Seraph Weakness",
    "category": "Bestiary",
    "triggerType": "manual",
    "triggerId": "bestiary_fallen_seraph@5",
    "threat": "Manual Study // Bestiary",
    "body": "Bestiary tier 3: Every phase adds pressure. Watch the attack order, move before the beam settles, and treat the final phase like a race."
  },
  {
    "code": "LORE-BLACKHOLE-BASIC",
    "sourceId": "lore_blackhole_basic",
    "title": "Black-Hole Lore: First Contact",
    "hiddenTitle": "Unknown Gravity Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:blackholecore|demontimessntwo:blackhole_core_item|demontimessntwo:stabilized_blackhole_fragment",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 1: Black-hole materials are not just crafting parts. They are contained collapse, useful only while the container keeps winning."
  },
  {
    "code": "LORE-BLACK-HOLE-RING-BASIC",
    "sourceId": "lore_black_hole_ring_basic",
    "title": "Black Hole Ring: Dormant",
    "hiddenTitle": "Unknown Ring Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:black_hole_ring",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 1: The Black Hole Ring is a worn singularity ward. Even idle, it listens for nearby gravity."
  },
  {
    "code": "LORE-BLACK-HOLE-RING-USED",
    "sourceId": "lore_black_hole_ring_used",
    "title": "Black Hole Ring: Awake",
    "hiddenTitle": "Unknown Active Ring Lore",
    "category": "Lore",
    "triggerType": "use",
    "triggerId": "demontimessntwo:black_hole_ring",
    "threat": "Use Record // Lore",
    "body": "Item lore tier 2: Using the ring teaches the Archive its real trick: nearby drops bend toward the wearer, and black-hole damage loses its bite."
  },
  {
    "code": "LORE-BLACKHOLE-STAFF-USED",
    "sourceId": "lore_blackhole_staff_used",
    "title": "Gravity Staff: Handling Notes",
    "hiddenTitle": "Unknown Staff Use Lore",
    "category": "Lore",
    "triggerType": "use",
    "triggerId": "demontimessntwo:blackhole_staff|demontimessntwo:stabilized_blackhole_staff|demontimessntwo:event_horizon_staff|demontimessntwo:singularity_staff",
    "threat": "Use Record // Lore",
    "body": "Item lore tier 2: The staff line is not a wand. It is a controlled failure state: aim, release, and hope the world agrees with your math."
  },
  {
    "code": "LORE-BLACKHOLE-STAFF-FULL",
    "sourceId": "lore_blackhole_staff_full",
    "title": "Gravity Staff: Complete Line",
    "hiddenTitle": "Unknown Complete Staff Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:event_horizon_staff|demontimessntwo:singularity_staff",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 3: The higher staff tiers stop asking whether gravity should obey. They begin deciding where gravity is allowed to exist."
  },
  {
    "code": "LORE-HEAVENS-WRATH-BASIC",
    "sourceId": "lore_heavens_wrath_basic",
    "title": "Heaven's Wrath: First Edge",
    "hiddenTitle": "Unknown Blade Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:heavens_wrath|demontimessntwo:blessed_aerolite_sword|demontimessntwo:celestial_blade",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 1: Heaven's Wrath is a weapon path, but its theme is judgment: ordinary metal taught to remember the sky."
  },
  {
    "code": "LORE-HEAVENS-WRATH-USED",
    "sourceId": "lore_heavens_wrath_used",
    "title": "Heaven's Wrath: In Motion",
    "hiddenTitle": "Unknown Blade Use Lore",
    "category": "Lore",
    "triggerType": "use",
    "triggerId": "demontimessntwo:heavens_wrath|demontimessntwo:blessed_aerolite_sword|demontimessntwo:celestial_blade|demontimessntwo:true_heavens_wrath",
    "threat": "Use Record // Lore",
    "body": "Item lore tier 2: In use, the blade behaves like a verdict. Its power belongs to timing, range, and restraint."
  },
  {
    "code": "LORE-HEAVENS-WRATH-FULL",
    "sourceId": "lore_heavens_wrath_full",
    "title": "True Heaven's Wrath",
    "hiddenTitle": "Unknown True Blade Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:true_heavens_wrath",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 3: True Heaven's Wrath is the line completed: not a sword that became holy, but a holy sentence given an edge."
  },
  {
    "code": "LORE-TITAN-REMNANT-BASIC",
    "sourceId": "lore_titan_remnant_basic",
    "title": "Titan Remnant: Bone Memory",
    "hiddenTitle": "Unknown Titan Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:titan_remnant|demontimessntwo:titanremanent",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 1: Titan remnants are not dead material. They are leftovers with opinions."
  },
  {
    "code": "LORE-TITAN-REMNANT-FULL",
    "sourceId": "lore_titan_remnant_full",
    "title": "Titan Remnant: Altered Forms",
    "hiddenTitle": "Unknown Altered Titan Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:blessed_titan_remnant|demontimessntwo:concealed_titan_remnant|demontimessntwo:blood_stabilized_remnant|demontimessntwo:titan_bound_relic",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 3: Altered remnants reveal the Titan path: blessing, concealment, blood stabilization, and finally binding."
  },
  {
    "code": "LORE-PURIFIER-CORES-BASIC",
    "sourceId": "lore_purifier_cores_basic",
    "title": "Purifier Cores: First Circuit",
    "hiddenTitle": "Unknown Core Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:basic_purifier_core|demontimessntwo:angelic_core|demontimessntwo:abyssal_core|demontimessntwo:celestial_core|demontimessntwo:blood_core|demontimessntwo:verdant_core|demontimessntwo:infernal_core|demontimessntwo:echo_core",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 1: Purifier cores are moral machinery. Each core changes what the machine thinks clean means."
  },
  {
    "code": "LORE-INFUSION-BOOKS-FULL",
    "sourceId": "lore_infusion_books_full",
    "title": "Infusion Books: Marginalia",
    "hiddenTitle": "Unknown Infusion Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:restored_infusion_book|demontimessntwo:celestial_infusion_book|demontimessntwo:abyssal_infusion_book",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 3: The upgraded infusion books do not merely list recipes. They argue with the reader about what transformation should cost."
  },
  {
    "code": "LORE-UPGRADE-TABLE-DEEPER",
    "sourceId": "lore_upgrade_table_deeper",
    "title": "Upgrade Table: Deeper Work",
    "hiddenTitle": "Unknown Upgrade Lore",
    "category": "Lore",
    "triggerType": "block",
    "triggerId": "demontimessntwo:upgrade_table",
    "threat": "Block Contact // Lore",
    "body": "Upgrade lore: The table can safely improve equipment for a while. Past that, power needs stabilizing or the item starts fighting back."
  },
  {
    "code": "LORE-UPGRADE-CATALYSTS-BASIC",
    "sourceId": "lore_upgrade_catalysts_basic",
    "title": "Upgrade Catalysts: Pressure",
    "hiddenTitle": "Unknown Catalyst Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:upgrade_catalyst|demontimessntwo:lesser_upgrade_catalyst|demontimessntwo:focused_upgrade_catalyst|demontimessntwo:empowered_upgrade_catalyst|demontimessntwo:aerolite_upgrade_catalyst|demontimessntwo:celestial_upgrade_catalyst|demontimessntwo:titan_upgrade_catalyst|demontimessntwo:volatile_upgrade_catalyst",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 1: Catalysts push an item toward a better version of itself. Better does not always mean safer."
  },
  {
    "code": "LORE-UPGRADE-CATALYSTS-FULL",
    "sourceId": "lore_upgrade_catalysts_full",
    "title": "Upgrade Catalysts: Overlimit",
    "hiddenTitle": "Unknown Overlimit Lore",
    "category": "Lore",
    "triggerType": "item",
    "triggerId": "demontimessntwo:celestial_upgrade_catalyst|demontimessntwo:titan_upgrade_catalyst|demontimessntwo:volatile_upgrade_catalyst",
    "threat": "Item Recovered // Lore",
    "body": "Item lore tier 3: High-tier catalysts are overlimit tools. They should pair with stabilizers when upgrades move past the safe range."
  },
  {
    "code": "LORE-FALLING-BAUBLES-USED",
    "sourceId": "lore_falling_baubles_used",
    "title": "Bauble Lore: Falling Refused",
    "hiddenTitle": "Unknown Falling Bauble Lore",
    "category": "Lore",
    "triggerType": "use",
    "triggerId": "demontimessntwo:angelic_feather_charm|demontimessntwo:celestial_amulet|demontimessntwo:astral_ring",
    "threat": "Use Record // Lore",
    "body": "Use lore: Falling baubles do not remove gravity. They negotiate with it every tick you are losing the argument."
  },
  {
    "code": "LORE-LIFE-BAUBLES-USED",
    "sourceId": "lore_life_baubles_used",
    "title": "Bauble Lore: Emergency Mercy",
    "hiddenTitle": "Unknown Life Bauble Lore",
    "category": "Lore",
    "triggerType": "use",
    "triggerId": "demontimessntwo:grace_locket|demontimessntwo:titan_heart_pendant|demontimessntwo:blood_pact_ring|demontimessntwo:verdant_ring",
    "threat": "Use Record // Lore",
    "body": "Use lore: Life baubles wait until the body is scared enough to listen, then spend their charge to keep the wearer moving."
  },
  {
    "code": "LORE-ABYSSAL-WARDS-USED",
    "sourceId": "lore_abyssal_wards_used",
    "title": "Bauble Lore: Warding the Void",
    "hiddenTitle": "Unknown Warding Lore",
    "category": "Lore",
    "triggerType": "use",
    "triggerId": "demontimessntwo:abyssal_warding_charm|demontimessntwo:reinforced_abyssal_warding_charm|demontimessntwo:celestial_abyssal_warding_charm",
    "threat": "Use Record // Lore",
    "body": "Use lore: Abyssal wards do not block the void. They teach the void to take less."
  },
  {
    "code": "RITUAL-CLUE-ALTAR-FOUND",
    "sourceId": "ritual_clue_altar_found",
    "title": "Ritual Clue: The Altar Listens",
    "hiddenTitle": "Unknown Altar Clue",
    "category": "Rituals",
    "triggerType": "block",
    "triggerId": "demontimessntwo:heavenly_altar",
    "threat": "Block Contact // Rituals",
    "body": "Ritual clue: The altar reacts to attention before it reacts to offerings. Bring tools, symbols, and materials that already belong to Heaven."
  },
  {
    "code": "RITUAL-CLUE-TOOLS",
    "sourceId": "ritual_clue_tools",
    "title": "Ritual Clue: Cup and Knife",
    "hiddenTitle": "Unknown Tool Clue",
    "category": "Rituals",
    "triggerType": "item",
    "triggerId": "demontimessntwo:goblet|demontimessntwo:athame",
    "threat": "Item Recovered // Rituals",
    "body": "Ritual clue: The Goblet receives. The Athame divides. Together they tell the altar that this is not ordinary crafting."
  },
  {
    "code": "RITUAL-CLUE-FIRST-LIGHT",
    "sourceId": "ritual_clue_first_light",
    "title": "Ritual Clue: First Light",
    "hiddenTitle": "Unknown Feather Clue",
    "category": "Rituals",
    "triggerType": "item",
    "triggerId": "demontimessntwo:angelic_feather|demontimessntwo:gildedfeather|demontimessntwo:gilded_feather",
    "threat": "Item Recovered // Rituals",
    "body": "Ritual clue: Feather offerings belong to gentler rites. They open early Heaven paths, but should not be the only efficient ritual forever."
  },
  {
    "code": "RITUAL-CLUE-GRAVITY",
    "sourceId": "ritual_clue_gravity",
    "title": "Ritual Clue: Gravity Offering",
    "hiddenTitle": "Unknown Gravity Clue",
    "category": "Rituals",
    "triggerType": "item",
    "triggerId": "demontimessntwo:blackholecore|demontimessntwo:blackhole_core_item|demontimessntwo:celestial_singularity",
    "threat": "Item Recovered // Rituals",
    "body": "Ritual clue: Black-hole offerings should ask for power, staff progression, or expensive singular rewards. They should never feel cheap."
  },
  {
    "code": "RITUAL-CLUE-TITAN",
    "sourceId": "ritual_clue_titan",
    "title": "Ritual Clue: Titan Offering",
    "hiddenTitle": "Unknown Titan Clue",
    "category": "Rituals",
    "triggerType": "item",
    "triggerId": "demontimessntwo:titan_remnant|demontimessntwo:titanremanent",
    "threat": "Item Recovered // Rituals",
    "body": "Ritual clue: Titan offerings belong to endurance, binding, belts, heavy survival, and boss-tier upgrades."
  },
  {
    "code": "RITUAL-CLUE-PURIFIER",
    "sourceId": "ritual_clue_purifier",
    "title": "Ritual Clue: Purifier Logic",
    "hiddenTitle": "Unknown Purifier Clue",
    "category": "Rituals",
    "triggerType": "block",
    "triggerId": "demontimessntwo:purifier",
    "threat": "Block Contact // Rituals",
    "body": "Ritual clue: Purifier rites should separate corruption from material, but the output should remember what it used to be."
  },
  {
    "code": "RITUAL-CLUE-CACHE",
    "sourceId": "ritual_clue_cache",
    "title": "Ritual Clue: Cache Key",
    "hiddenTitle": "Unknown Cache Clue",
    "category": "Rituals",
    "triggerType": "item",
    "triggerId": "demontimessntwo:heavenly_cache_key_fragment|demontimessntwo:heavenly_cache_key",
    "threat": "Item Recovered // Rituals",
    "body": "Ritual clue: A complete key should open a cache. A broken key should teach the player that locked Heaven rewards are built, not simply found."
  },
  {
    "code": "ALTAR-UNSTABLE-FAILURE",
    "sourceId": "altar_unstable_failure",
    "title": "Unstable Altar Failure",
    "hiddenTitle": "Unknown Altar Failure",
    "category": "Rituals",
    "triggerType": "discovery",
    "triggerId": "altar_unstable_failure",
    "threat": "Discovery Record // Rituals",
    "body": "An altar without a stabilizer circle can fail raw. The rite may fizzle, backlash, drain favor, or wake nearby hostile things."
  },
  {
    "code": "ALTAR-STABILIZED-FAILURE",
    "sourceId": "altar_stabilized_failure",
    "title": "Stabilized Altar Failure",
    "hiddenTitle": "Unknown Stabilized Failure",
    "category": "Rituals",
    "triggerType": "discovery",
    "triggerId": "altar_stabilized_failure",
    "threat": "Discovery Record // Rituals",
    "body": "A stabilizer circle does not make every rite succeed. It makes failure survivable. The circle catches the worst of the mistake."
  },
  {
    "code": "ALTAR-VOLATILE-FAILURE",
    "sourceId": "altar_volatile_failure",
    "title": "Volatile Stabilizer Backlash",
    "hiddenTitle": "Unknown Volatile Failure",
    "category": "Rituals",
    "triggerType": "discovery",
    "triggerId": "altar_volatile_failure",
    "threat": "Discovery Record // Rituals",
    "body": "Volatile stabilizers feed more power into the circle. They improve success, but when they go wrong, they go wrong loudly."
  }
];

const STORAGE_KEY = "demontime.redArchive.unlocked";
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => Array.from(document.querySelectorAll(selector));
const animeApi = window.anime || null;
const animate = animeApi?.animate || null;
const stagger = animeApi?.stagger || ((n) => (_, i) => i * n);

const MINECRAFT_COLOR_CLASSES = {
  "0": "mc-black",
  "1": "mc-dark-blue",
  "2": "mc-dark-green",
  "3": "mc-dark-aqua",
  "4": "mc-dark-red",
  "5": "mc-dark-purple",
  "6": "mc-gold",
  "7": "mc-gray",
  "8": "mc-dark-gray",
  "9": "mc-blue",
  a: "mc-green",
  b: "mc-aqua",
  c: "mc-red",
  d: "mc-light-purple",
  e: "mc-yellow",
  f: "mc-white"
};

const MINECRAFT_FORMAT_CLASSES = {
  k: "mc-obfuscated",
  l: "mc-bold",
  m: "mc-strikethrough",
  n: "mc-underline",
  o: "mc-italic"
};

const OBFUSCATE_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789█▓▒░<>/\\{}[]!?$%#@*&+-=";

const els = {
  input: $("#code-input"),
  submit: $("#submit-code"),
  status: $("#archive-status"),
  result: $("#result-panel"),
  recordTitle: $("#record-title"),
  recordMeta: $("#record-meta"),
  recordBody: $("#record-body"),
  recordWarning: $("#record-warning"),
  copy: $("#copy-record"),
  reset: $("#reset-archive"),
  grid: $("#archive-grid"),
  unlockedCount: $("#unlocked-count"),
  totalCount: $("#total-count")
};

const VALID_ARCHIVE_CODES = new Set(RED_ARCHIVE_RECORDS.map((record) => record.code));
let unlocked = new Set(loadUnlockedCodes().filter((code) => VALID_ARCHIVE_CODES.has(code)));
let activeRecord = null;
let obfuscationTimer = null;

boot();

function boot() {
  els.totalCount.textContent = RED_ARCHIVE_RECORDS.length;
  renderGrid();
  bindEvents();
  startAmbientAnimations();

  if (animate) {
    animate(".eyebrow", { opacity: [0, 1], translateY: [-8, 0], duration: 900, delay: 150, ease: "outQuad" });
    animate(".title", { opacity: [0, 1], scale: [0.94, 1], duration: 1200, delay: 300, ease: "outExpo" });
    animate(".subtitle", { opacity: [0, 1], translateY: [14, 0], duration: 900, delay: 620, ease: "outQuad" });
    animate(".terminal-card", { opacity: [0, 1], translateY: [32, 0], duration: 900, delay: 820, ease: "outExpo" });
  }
}

function bindEvents() {
  els.submit.addEventListener("click", handleSubmit);
  els.input.addEventListener("keydown", (event) => {
    if (event.key === "Enter") handleSubmit();
  });

  els.reset.addEventListener("click", () => {
    unlocked = new Set();
    localStorage.removeItem(STORAGE_KEY);
    activeRecord = null;
    els.result.classList.add("hidden");
    setStatus("ARCHIVE PURGED");
    renderGrid();
    pulseElement(els.reset);
  });

  els.copy.addEventListener("click", async () => {
    if (!activeRecord) return;
    const text = `${stripMinecraftFormatting(activeRecord.title)}\n${activeRecord.code}\n${stripMinecraftFormatting(activeRecord.category)}\n\n${stripMinecraftFormatting(activeRecord.body)}`;
    try {
      await navigator.clipboard.writeText(text);
      setStatus("ENTRY COPIED");
      els.copy.textContent = "Copied";
      setTimeout(() => (els.copy.textContent = "Copy entry"), 1200);
    } catch {
      setStatus("COPY BLOCKED");
    }
  });
}

function handleSubmit() {
  const normalized = normalizeCode(els.input.value);
  const record = RED_ARCHIVE_RECORDS.find((item) => normalizeCode(item.code) === normalized || normalizeCode(item.sourceId) === normalized);

  if (!normalized) {
    setStatus("AWAITING CODE");
    shake(els.input);
    return;
  }

  if (!record) {
    setStatus("ACCESS DENIED");
    showDenied();
    return;
  }

  unlocked.add(record.code);
  saveUnlockedCodes([...unlocked]);
  revealRecord(record);
  renderGrid();
}

function revealRecord(record) {
  activeRecord = record;
  setStatus("DECRYPTING");
  els.result.classList.remove("hidden");
  setFormattedContent(els.recordTitle, record.title);
  setFormattedContent(els.recordMeta, `${record.code} // ${record.category}`);
  setFormattedContent(els.recordWarning, record.threat);
  els.recordBody.innerHTML = "";

  if (animate) {
    animate(els.result, { opacity: [0, 1], translateY: [24, 0], scale: [0.98, 1], duration: 620, ease: "outExpo" });
    animate(".record-label, #record-title, #record-meta, .record-footer", {
      opacity: [0, 1],
      translateX: [-12, 0],
      delay: stagger(70),
      duration: 520,
      ease: "outQuad"
    });
  }

  typeFormattedText(els.recordBody, record.body, 15, () => setStatus("RECORD UNLOCKED"));
}

function showDenied() {
  els.result.classList.remove("hidden");
  els.recordTitle.textContent = "Record Not Found";
  els.recordMeta.textContent = "UNKNOWN-CODE // ACCESS REFUSED";
  els.recordWarning.textContent = "The archive does not know this name.";
  els.recordBody.textContent = "No matching record exists. Check the recovered code, remove extra symbols, or seek another archive fragment in-game.";
  activeRecord = null;
  shake(els.result);
}

function renderGrid() {
  els.unlockedCount.textContent = unlocked.size;
  els.grid.innerHTML = RED_ARCHIVE_RECORDS.map((record) => {
    const isUnlocked = unlocked.has(record.code);
    return `
      <article class="archive-card ${isUnlocked ? "" : "locked"}">
        <div class="code">${isUnlocked ? escapeHtml(record.code) : "LOCKED-RECORD"}</div>
        <h3>${isUnlocked ? renderMinecraftText(record.title) : escapeHtml(record.hiddenTitle || "Unknown Record")}</h3>
        <p>${isUnlocked ? escapeHtml(preview(stripMinecraftFormatting(record.body))) : "This file is sealed. Recover its code in-game to decrypt the entry."}</p>
        ${isUnlocked ? `<button class="ghost-button reopen" data-code="${escapeAttr(record.code)}">Open</button>` : ""}
      </article>
    `;
  }).join("");

  $$(".reopen").forEach((button) => {
    button.addEventListener("click", () => {
      const record = RED_ARCHIVE_RECORDS.find((item) => item.code === button.dataset.code);
      if (record) revealRecord(record);
    });
  });

  restartObfuscatedText();

  if (animate) {
    animate(".archive-card", {
      opacity: [0, 1],
      translateY: [16, 0],
      delay: stagger(45),
      duration: 480,
      ease: "outQuad"
    });
  }
}

function startAmbientAnimations() {
  if (!animate) return;

  animate(".sigil-ring", {
    rotate: "360deg",
    duration: 48000,
    loop: true,
    ease: "linear"
  });

  animate(".sigil", {
    scale: [0.92, 1.14],
    opacity: [0.55, 1],
    delay: stagger(220),
    duration: 2200,
    alternate: true,
    loop: true,
    ease: "inOutSine"
  });

  animate(".lights span", {
    opacity: [0.35, 1],
    delay: stagger(260),
    duration: 900,
    alternate: true,
    loop: true,
    ease: "inOutSine"
  });
}

function setFormattedContent(element, text) {
  element.innerHTML = renderMinecraftText(text);
  restartObfuscatedText();
}

function typeFormattedText(element, text, speed = 18, done = () => {}) {
  let index = 0;
  element.innerHTML = "";

  const timer = setInterval(() => {
    index += 1;

    // Formatting codes should apply instantly instead of appearing as typed text.
    while (text.charAt(index - 1) === "§" && index < text.length) {
      index += 1;
    }

    element.innerHTML = renderMinecraftText(text.slice(0, index));

    if (index >= text.length) {
      clearInterval(timer);
      restartObfuscatedText();
      done();
    }
  }, speed);
}

function renderMinecraftText(text) {
  const state = createFormattingState();
  let html = "";
  let buffer = "";

  const flush = () => {
    if (!buffer) return;

    const classes = [];
    if (state.colorClass) classes.push(state.colorClass);
    if (state.obfuscated) classes.push(MINECRAFT_FORMAT_CLASSES.k);
    if (state.bold) classes.push(MINECRAFT_FORMAT_CLASSES.l);
    if (state.strikethrough) classes.push(MINECRAFT_FORMAT_CLASSES.m);
    if (state.underline) classes.push(MINECRAFT_FORMAT_CLASSES.n);
    if (state.italic) classes.push(MINECRAFT_FORMAT_CLASSES.o);

    const classAttr = classes.length ? ` class="${classes.join(" ")}"` : "";
    const styleAttr = state.colorStyle ? ` style="color: ${state.colorStyle}"` : "";
    const originalAttr = state.obfuscated ? ` data-original="${escapeAttr(buffer)}"` : "";
    html += `<span${classAttr}${styleAttr}${originalAttr}>${escapeHtml(buffer).replace(/\n/g, "<br>")}</span>`;
    buffer = "";
  };

  for (let i = 0; i < String(text || "").length; i += 1) {
    const char = text[i];

    if (char === "§" && i + 1 < text.length) {
      const code = text[i + 1].toLowerCase();
      flush();

      if (code === "x") {
        const hex = readMinecraftHexColor(text, i);
        if (hex) {
          applyColor(state, null, `#${hex.value}`);
          i = hex.endIndex;
          continue;
        }
      }

      if (MINECRAFT_COLOR_CLASSES[code]) {
        applyColor(state, MINECRAFT_COLOR_CLASSES[code], null);
        i += 1;
        continue;
      }

      if (MINECRAFT_FORMAT_CLASSES[code]) {
        applyFormat(state, code);
        i += 1;
        continue;
      }

      if (code === "r") {
        resetFormattingState(state);
        i += 1;
        continue;
      }

      // Unknown § codes stay visible so mistakes are easier to catch while editing.
      buffer += char;
      continue;
    }

    buffer += char;
  }

  flush();
  return html;
}

function readMinecraftHexColor(text, startIndex) {
  // Supports Java's §x§R§R§G§G§B§B style hex formatting.
  let cursor = startIndex + 2;
  let value = "";

  for (let part = 0; part < 6; part += 1) {
    if (text[cursor] !== "§" || !/[0-9a-fA-F]/.test(text[cursor + 1] || "")) return null;
    value += text[cursor + 1];
    cursor += 2;
  }

  return { value, endIndex: cursor - 1 };
}

function createFormattingState() {
  return {
    colorClass: null,
    colorStyle: null,
    obfuscated: false,
    bold: false,
    strikethrough: false,
    underline: false,
    italic: false
  };
}

function resetFormattingState(state) {
  state.colorClass = null;
  state.colorStyle = null;
  state.obfuscated = false;
  state.bold = false;
  state.strikethrough = false;
  state.underline = false;
  state.italic = false;
}

function applyColor(state, colorClass, colorStyle) {
  // Minecraft color codes reset active formatting.
  resetFormattingState(state);
  state.colorClass = colorClass;
  state.colorStyle = colorStyle;
}

function applyFormat(state, code) {
  if (code === "k") state.obfuscated = true;
  if (code === "l") state.bold = true;
  if (code === "m") state.strikethrough = true;
  if (code === "n") state.underline = true;
  if (code === "o") state.italic = true;
}

function restartObfuscatedText() {
  if (obfuscationTimer) clearInterval(obfuscationTimer);

  const tick = () => {
    $$(".mc-obfuscated").forEach((span) => {
      const original = span.dataset.original || span.textContent || "";
      span.textContent = randomObfuscatedString(original);
    });
  };

  tick();
  obfuscationTimer = setInterval(tick, 82);
}

function randomObfuscatedString(original) {
  return Array.from(original).map((char) => {
    if (/\s/.test(char)) return char;
    return OBFUSCATE_CHARS[Math.floor(Math.random() * OBFUSCATE_CHARS.length)];
  }).join("");
}

function stripMinecraftFormatting(text) {
  return String(text || "").replace(/§x(§[0-9a-fA-F]){6}/g, "").replace(/§[0-9a-fk-orA-FK-OR]/g, "");
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function escapeAttr(value) {
  return escapeHtml(value).replace(/`/g, "&#096;");
}

function normalizeCode(code) {
  return String(code || "")
    .trim()
    .toUpperCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^A-Z0-9-]/g, "")
    .replace(/-+/g, "-");
}

function loadUnlockedCodes() {
  try {
    const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function saveUnlockedCodes(codes) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(codes));
}

function preview(text) {
  return text.length > 116 ? `${text.slice(0, 116)}…` : text;
}

function setStatus(text) {
  els.status.textContent = text;
  pulseElement(els.status);
}

function pulseElement(target) {
  if (!animate || !target) return;
  animate(target, { scale: [1, 1.04, 1], duration: 360, ease: "outQuad" });
}

function shake(target) {
  if (!animate || !target) return;
  animate(target, {
    translateX: [0, -8, 8, -5, 5, 0],
    duration: 420,
    ease: "outQuad"
  });
}
